global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "webapp"
    static_configs:
      - targets: [ "web:19003" ]
    metrics_path: /metrics

  - job_name: "authpost"
    static_configs:
      - targets: [ "aap:19101" ]
    metrics_path: /metrics

  - job_name: "newsfeed"
    static_configs:
      - targets: [ "newsfeed:19102" ]
    metrics_path: /metrics

  - job_name: "newsfeed_publishing"
    static_configs:
      - targets: [ "nfp:19104" ]
    metrics_path: /metrics
