// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: authpost.proto

package authpost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_OK        UserStatus = 0
	UserStatus_NOT_FOUND UserStatus = 1
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
	}
	UserStatus_value = map[string]int32{
		"OK":        0,
		"NOT_FOUND": 1,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authpost_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_authpost_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{0}
}

type ActionStatus int32

const (
	ActionStatus_SUCCEEDED ActionStatus = 0
	ActionStatus_FAILED    ActionStatus = 1
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "SUCCEEDED",
		1: "FAILED",
	}
	ActionStatus_value = map[string]int32{
		"SUCCEEDED": 0,
		"FAILED":    1,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authpost_proto_enumTypes[1].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_authpost_proto_enumTypes[1]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{1}
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string                 `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_authpost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

type UserDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string                 `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Dob           int64                  `protobuf:"varint,6,opt,name=dob,proto3" json:"dob,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailInfo) Reset() {
	*x = UserDetailInfo{}
	mi := &file_authpost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailInfo) ProtoMessage() {}

func (x *UserDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailInfo.ProtoReflect.Descriptor instead.
func (*UserDetailInfo) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetailInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDetailInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserDetailInfo) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *UserDetailInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserDetailInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserDetailInfo) GetDob() int64 {
	if x != nil {
		return x.Dob
	}
	return 0
}

func (x *UserDetailInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        UserStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=authpost.UserStatus" json:"status,omitempty"`
	Info          *UserDetailInfo        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResult) Reset() {
	*x = UserResult{}
	mi := &file_authpost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResult) ProtoMessage() {}

func (x *UserResult) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResult.ProtoReflect.Descriptor instead.
func (*UserResult) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{2}
}

func (x *UserResult) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_OK
}

func (x *UserResult) GetInfo() *UserDetailInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UserFollower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*UserInfo            `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFollower) Reset() {
	*x = UserFollower{}
	mi := &file_authpost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollower) ProtoMessage() {}

func (x *UserFollower) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollower.ProtoReflect.Descriptor instead.
func (*UserFollower) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{3}
}

func (x *UserFollower) GetFollowers() []*UserInfo {
	if x != nil {
		return x.Followers
	}
	return nil
}

type UserAndFollower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Follower      *UserInfo              `protobuf:"bytes,2,opt,name=follower,proto3" json:"follower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAndFollower) Reset() {
	*x = UserAndFollower{}
	mi := &file_authpost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAndFollower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAndFollower) ProtoMessage() {}

func (x *UserAndFollower) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAndFollower.ProtoReflect.Descriptor instead.
func (*UserAndFollower) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{4}
}

func (x *UserAndFollower) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserAndFollower) GetFollower() *UserInfo {
	if x != nil {
		return x.Follower
	}
	return nil
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_authpost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type Post struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PostId           int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentText      string                 `protobuf:"bytes,3,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	ContentImagePath string                 `protobuf:"bytes,4,opt,name=content_image_path,json=contentImagePath,proto3" json:"content_image_path,omitempty"`
	Visible          bool                   `protobuf:"varint,5,opt,name=visible,proto3" json:"visible,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_authpost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{6}
}

func (x *Post) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Post) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *Post) GetContentImagePath() string {
	if x != nil {
		return x.ContentImagePath
	}
	return ""
}

func (x *Post) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ActionStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=authpost.ActionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_authpost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_authpost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_authpost_proto_rawDescGZIP(), []int{7}
}

func (x *ActionResult) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_SUCCEEDED
}

var File_authpost_proto protoreflect.FileDescriptor

const file_authpost_proto_rawDesc = "" +
	"\n" +
	"\x0eauthpost.proto\x12\bauthpost\"e\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12#\n" +
	"\ruser_password\x18\x03 \x01(\tR\fuserPassword\"\xcf\x01\n" +
	"\x0eUserDetailInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12#\n" +
	"\ruser_password\x18\x03 \x01(\tR\fuserPassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x10\n" +
	"\x03dob\x18\x06 \x01(\x03R\x03dob\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"h\n" +
	"\n" +
	"UserResult\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.authpost.UserStatusR\x06status\x12,\n" +
	"\x04info\x18\x02 \x01(\v2\x18.authpost.UserDetailInfoR\x04info\"@\n" +
	"\fUserFollower\x120\n" +
	"\tfollowers\x18\x01 \x03(\v2\x12.authpost.UserInfoR\tfollowers\"i\n" +
	"\x0fUserAndFollower\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.authpost.UserInfoR\x04user\x12.\n" +
	"\bfollower\x18\x02 \x01(\v2\x12.authpost.UserInfoR\bfollower\")\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"\xc2\x01\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fcontent_text\x18\x03 \x01(\tR\vcontentText\x12,\n" +
	"\x12content_image_path\x18\x04 \x01(\tR\x10contentImagePath\x12\x18\n" +
	"\avisible\x18\x05 \x01(\bR\avisible\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\">\n" +
	"\fActionResult\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.authpost.ActionStatusR\x06status*#\n" +
	"\n" +
	"UserStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01*)\n" +
	"\fActionStatus\x12\r\n" +
	"\tSUCCEEDED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012\xa3\x03\n" +
	"\x13AuthenticateAndPost\x12E\n" +
	"\x17CheckUserAuthentication\x12\x12.authpost.UserInfo\x1a\x14.authpost.UserResult\"\x00\x12>\n" +
	"\n" +
	"CreateUser\x12\x18.authpost.UserDetailInfo\x1a\x14.authpost.UserResult\"\x00\x12<\n" +
	"\bEditUser\x12\x18.authpost.UserDetailInfo\x1a\x14.authpost.UserResult\"\x00\x12?\n" +
	"\x0fGetUserFollower\x12\x12.authpost.UserInfo\x1a\x16.authpost.UserFollower\"\x00\x12A\n" +
	"\n" +
	"FollowUser\x12\x19.authpost.UserAndFollower\x1a\x16.authpost.ActionResult\"\x00\x12C\n" +
	"\fUnfollowUser\x12\x19.authpost.UserAndFollower\x1a\x16.authpost.ActionResult\"\x00B\fZ\n" +
	".;authpostb\x06proto3"

var (
	file_authpost_proto_rawDescOnce sync.Once
	file_authpost_proto_rawDescData []byte
)

func file_authpost_proto_rawDescGZIP() []byte {
	file_authpost_proto_rawDescOnce.Do(func() {
		file_authpost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authpost_proto_rawDesc), len(file_authpost_proto_rawDesc)))
	})
	return file_authpost_proto_rawDescData
}

var file_authpost_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_authpost_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_authpost_proto_goTypes = []any{
	(UserStatus)(0),         // 0: authpost.UserStatus
	(ActionStatus)(0),       // 1: authpost.ActionStatus
	(*UserInfo)(nil),        // 2: authpost.UserInfo
	(*UserDetailInfo)(nil),  // 3: authpost.UserDetailInfo
	(*UserResult)(nil),      // 4: authpost.UserResult
	(*UserFollower)(nil),    // 5: authpost.UserFollower
	(*UserAndFollower)(nil), // 6: authpost.UserAndFollower
	(*GetPostRequest)(nil),  // 7: authpost.GetPostRequest
	(*Post)(nil),            // 8: authpost.Post
	(*ActionResult)(nil),    // 9: authpost.ActionResult
}
var file_authpost_proto_depIdxs = []int32{
	0,  // 0: authpost.UserResult.status:type_name -> authpost.UserStatus
	3,  // 1: authpost.UserResult.info:type_name -> authpost.UserDetailInfo
	2,  // 2: authpost.UserFollower.followers:type_name -> authpost.UserInfo
	2,  // 3: authpost.UserAndFollower.user:type_name -> authpost.UserInfo
	2,  // 4: authpost.UserAndFollower.follower:type_name -> authpost.UserInfo
	1,  // 5: authpost.ActionResult.status:type_name -> authpost.ActionStatus
	2,  // 6: authpost.AuthenticateAndPost.CheckUserAuthentication:input_type -> authpost.UserInfo
	3,  // 7: authpost.AuthenticateAndPost.CreateUser:input_type -> authpost.UserDetailInfo
	3,  // 8: authpost.AuthenticateAndPost.EditUser:input_type -> authpost.UserDetailInfo
	2,  // 9: authpost.AuthenticateAndPost.GetUserFollower:input_type -> authpost.UserInfo
	6,  // 10: authpost.AuthenticateAndPost.FollowUser:input_type -> authpost.UserAndFollower
	6,  // 11: authpost.AuthenticateAndPost.UnfollowUser:input_type -> authpost.UserAndFollower
	4,  // 12: authpost.AuthenticateAndPost.CheckUserAuthentication:output_type -> authpost.UserResult
	4,  // 13: authpost.AuthenticateAndPost.CreateUser:output_type -> authpost.UserResult
	4,  // 14: authpost.AuthenticateAndPost.EditUser:output_type -> authpost.UserResult
	5,  // 15: authpost.AuthenticateAndPost.GetUserFollower:output_type -> authpost.UserFollower
	9,  // 16: authpost.AuthenticateAndPost.FollowUser:output_type -> authpost.ActionResult
	9,  // 17: authpost.AuthenticateAndPost.UnfollowUser:output_type -> authpost.ActionResult
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_authpost_proto_init() }
func file_authpost_proto_init() {
	if File_authpost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authpost_proto_rawDesc), len(file_authpost_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authpost_proto_goTypes,
		DependencyIndexes: file_authpost_proto_depIdxs,
		EnumInfos:         file_authpost_proto_enumTypes,
		MessageInfos:      file_authpost_proto_msgTypes,
	}.Build()
	File_authpost_proto = out.File
	file_authpost_proto_goTypes = nil
	file_authpost_proto_depIdxs = nil
}
