version: '3'
services:

  web:
    build:
      context: .
      dockerfile: cmd/webapp/Dockerfile
      target: test_env
    image: webapp
    depends_on:
      - aap
    networks:
      - intranet
      - default
    hostname: web
    ports:
      - 19003:19003

  aap:
    build:
      context: .
      dockerfile: cmd/authpost/Dockerfile
      target: test_env
    image: authpost
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - intranet
    hostname: aap
    ports:
      - 19001:19001

  postgres:
    image: postgres
    volumes:
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf # Global default settings
      - ./data/postgres:/var/lib/postgresql/data # Data of databases
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: wander_sphere
    networks:
      - intranet
    hostname: postgres
    ports:
      - 5432:5432
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "wander_sphere" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    networks:
      - intranet
    hostname: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  intranet: {}
  default: {}
