# Configuration for authpost service (production)
port: 19001
postgres:
  dsn: "host=postgres port=5432 user=postgres password=123456 dbname=wander_sphere sslmode=disable"
  defaultStringSize: 256
  disableDatetimePrecision: true
  dontSupportRenameIndex: true
  skipInitializeWithVersion: false
redis:
  addr: "redis:6379"
  password: "2511"
newsfeed_publishing:
  hosts: ["nfp:19004"]
logger:
  level: "info"
  path: "logs/authpost.log" 