# Configuration for webapp service (local development)
port: 19003
logger:
  level: "debug"
  path: "logs/webapp.log"
api_version: ["v1"]
authenticate_and_post:
  hosts: ["localhost:19001"]
newsfeed:
  hosts: ["localhost:19002"]
redis:
  addr: "localhost:6379"
  password: ""
auth:
  session:
    cookie_name: "wandersphere_session"
    expiration_minutes: 1440  # 24 hours
    secure: true
    http_only: true
    same_site: "strict" 