# Configuration for local development
port: 19001
postgres:
  dsn: "host=localhost port=5432 user=postgres password=123456 dbname=wander_sphere sslmode=disable"
  defaultStringSize: 256
  disableDatetimePrecision: true
  dontSupportRenameIndex: true
  skipInitializeWithVersion: false
redis:
  addr: "localhost:6379"
  password: ""
newsfeed_publishing:
  hosts: ["localhost:19004"]
logger:
  level: "debug"
  path: "logs/authpost.log" 
auth:
  session:
    cookie_name: "wandersphere_session"
    expiration_minutes: 1440  # 24 hours
    secure: true
    http_only: true
    same_site: "strict" 