# Configuration for newsfeed publishing service
port: 19004
redis:
  addr: "redis:6379"
  password: ""
  db: 0
kafka:
  topic: "wander_sphere"
  brokers: ["kafka:9092"]
authenticate_and_post:
  hosts: ["aap:19001"]
logger:
  level: "debug"
  path: "logs/newsfeed_publishing.log" 