// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: newsfeed.proto

package __newsfeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsfeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsfeedRequest) Reset() {
	*x = NewsfeedRequest{}
	mi := &file_newsfeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsfeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsfeedRequest) ProtoMessage() {}

func (x *NewsfeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newsfeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsfeedRequest.ProtoReflect.Descriptor instead.
func (*NewsfeedRequest) Descriptor() ([]byte, []int) {
	return file_newsfeed_proto_rawDescGZIP(), []int{0}
}

func (x *NewsfeedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NewsfeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        []int64                `protobuf:"varint,1,rep,packed,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsfeedResponse) Reset() {
	*x = NewsfeedResponse{}
	mi := &file_newsfeed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsfeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsfeedResponse) ProtoMessage() {}

func (x *NewsfeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newsfeed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsfeedResponse.ProtoReflect.Descriptor instead.
func (*NewsfeedResponse) Descriptor() ([]byte, []int) {
	return file_newsfeed_proto_rawDescGZIP(), []int{1}
}

func (x *NewsfeedResponse) GetPostId() []int64 {
	if x != nil {
		return x.PostId
	}
	return nil
}

var File_newsfeed_proto protoreflect.FileDescriptor

const file_newsfeed_proto_rawDesc = "" +
	"\n" +
	"\x0enewsfeed.proto\x12\bnewsfeed\"*\n" +
	"\x0fNewsfeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"+\n" +
	"\x10NewsfeedResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x03(\x03R\x06postId2R\n" +
	"\bNewsfeed\x12F\n" +
	"\vGetNewsfeed\x12\x19.newsfeed.NewsfeedRequest\x1a\x1a.newsfeed.NewsfeedResponse\"\x00B\vZ\t.newsfeedb\x06proto3"

var (
	file_newsfeed_proto_rawDescOnce sync.Once
	file_newsfeed_proto_rawDescData []byte
)

func file_newsfeed_proto_rawDescGZIP() []byte {
	file_newsfeed_proto_rawDescOnce.Do(func() {
		file_newsfeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_newsfeed_proto_rawDesc), len(file_newsfeed_proto_rawDesc)))
	})
	return file_newsfeed_proto_rawDescData
}

var file_newsfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_newsfeed_proto_goTypes = []any{
	(*NewsfeedRequest)(nil),  // 0: newsfeed.NewsfeedRequest
	(*NewsfeedResponse)(nil), // 1: newsfeed.NewsfeedResponse
}
var file_newsfeed_proto_depIdxs = []int32{
	0, // 0: newsfeed.Newsfeed.GetNewsfeed:input_type -> newsfeed.NewsfeedRequest
	1, // 1: newsfeed.Newsfeed.GetNewsfeed:output_type -> newsfeed.NewsfeedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_newsfeed_proto_init() }
func file_newsfeed_proto_init() {
	if File_newsfeed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_newsfeed_proto_rawDesc), len(file_newsfeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newsfeed_proto_goTypes,
		DependencyIndexes: file_newsfeed_proto_depIdxs,
		MessageInfos:      file_newsfeed_proto_msgTypes,
	}.Build()
	File_newsfeed_proto = out.File
	file_newsfeed_proto_goTypes = nil
	file_newsfeed_proto_depIdxs = nil
}
