// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v7.34.1
// source: pkg/types/proto/newsfeed_publishing.proto

package newsfeed_publishing

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishPostResponse_PublishPostResponseStatus int32

const (
	PublishPostResponse_OK     PublishPostResponse_PublishPostResponseStatus = 0
	PublishPostResponse_FAILED PublishPostResponse_PublishPostResponseStatus = 1
)

// Enum value maps for PublishPostResponse_PublishPostResponseStatus.
var (
	PublishPostResponse_PublishPostResponseStatus_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	PublishPostResponse_PublishPostResponseStatus_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x PublishPostResponse_PublishPostResponseStatus) Enum() *PublishPostResponse_PublishPostResponseStatus {
	p := new(PublishPostResponse_PublishPostResponseStatus)
	*p = x
	return p
}

func (x PublishPostResponse_PublishPostResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishPostResponse_PublishPostResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_types_proto_newsfeed_publishing_proto_enumTypes[0].Descriptor()
}

func (PublishPostResponse_PublishPostResponseStatus) Type() protoreflect.EnumType {
	return &file_pkg_types_proto_newsfeed_publishing_proto_enumTypes[0]
}

func (x PublishPostResponse_PublishPostResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishPostResponse_PublishPostResponseStatus.Descriptor instead.
func (PublishPostResponse_PublishPostResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP(), []int{1, 0}
}

type UpdateEngagementScoreResponse_UpdateEngagementScoreStatus int32

const (
	UpdateEngagementScoreResponse_OK     UpdateEngagementScoreResponse_UpdateEngagementScoreStatus = 0
	UpdateEngagementScoreResponse_FAILED UpdateEngagementScoreResponse_UpdateEngagementScoreStatus = 1
)

// Enum value maps for UpdateEngagementScoreResponse_UpdateEngagementScoreStatus.
var (
	UpdateEngagementScoreResponse_UpdateEngagementScoreStatus_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	UpdateEngagementScoreResponse_UpdateEngagementScoreStatus_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x UpdateEngagementScoreResponse_UpdateEngagementScoreStatus) Enum() *UpdateEngagementScoreResponse_UpdateEngagementScoreStatus {
	p := new(UpdateEngagementScoreResponse_UpdateEngagementScoreStatus)
	*p = x
	return p
}

func (x UpdateEngagementScoreResponse_UpdateEngagementScoreStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateEngagementScoreResponse_UpdateEngagementScoreStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_types_proto_newsfeed_publishing_proto_enumTypes[1].Descriptor()
}

func (UpdateEngagementScoreResponse_UpdateEngagementScoreStatus) Type() protoreflect.EnumType {
	return &file_pkg_types_proto_newsfeed_publishing_proto_enumTypes[1]
}

func (x UpdateEngagementScoreResponse_UpdateEngagementScoreStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateEngagementScoreResponse_UpdateEngagementScoreStatus.Descriptor instead.
func (UpdateEngagementScoreResponse_UpdateEngagementScoreStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP(), []int{3, 0}
}

type PublishPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId int64 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *PublishPostRequest) Reset() {
	*x = PublishPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostRequest) ProtoMessage() {}

func (x *PublishPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostRequest.ProtoReflect.Descriptor instead.
func (*PublishPostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP(), []int{0}
}

func (x *PublishPostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PublishPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status PublishPostResponse_PublishPostResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=newsfeed_publishing.PublishPostResponse_PublishPostResponseStatus" json:"status,omitempty"`
}

func (x *PublishPostResponse) Reset() {
	*x = PublishPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostResponse) ProtoMessage() {}

func (x *PublishPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostResponse.ProtoReflect.Descriptor instead.
func (*PublishPostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP(), []int{1}
}

func (x *PublishPostResponse) GetStatus() PublishPostResponse_PublishPostResponseStatus {
	if x != nil {
		return x.Status
	}
	return PublishPostResponse_OK
}

type UpdateEngagementScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId        int64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	PostOwnerId   int64 `protobuf:"varint,2,opt,name=post_owner_id,json=postOwnerId,proto3" json:"post_owner_id,omitempty"`
	LikeCount     int64 `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64 `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CreatedAtUnix int64 `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
}

func (x *UpdateEngagementScoreRequest) Reset() {
	*x = UpdateEngagementScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEngagementScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEngagementScoreRequest) ProtoMessage() {}

func (x *UpdateEngagementScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEngagementScoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateEngagementScoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEngagementScoreRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdateEngagementScoreRequest) GetPostOwnerId() int64 {
	if x != nil {
		return x.PostOwnerId
	}
	return 0
}

func (x *UpdateEngagementScoreRequest) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *UpdateEngagementScoreRequest) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *UpdateEngagementScoreRequest) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type UpdateEngagementScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UpdateEngagementScoreResponse_UpdateEngagementScoreStatus `protobuf:"varint,1,opt,name=status,proto3,enum=newsfeed_publishing.UpdateEngagementScoreResponse_UpdateEngagementScoreStatus" json:"status,omitempty"`
}

func (x *UpdateEngagementScoreResponse) Reset() {
	*x = UpdateEngagementScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEngagementScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEngagementScoreResponse) ProtoMessage() {}

func (x *UpdateEngagementScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEngagementScoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateEngagementScoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEngagementScoreResponse) GetStatus() UpdateEngagementScoreResponse_UpdateEngagementScoreStatus {
	if x != nil {
		return x.Status
	}
	return UpdateEngagementScoreResponse_OK
}

var File_pkg_types_proto_newsfeed_publishing_proto protoreflect.FileDescriptor

var file_pkg_types_proto_newsfeed_publishing_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6e, 0x65, 0x77,
	0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x22, 0x46, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x13, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x42, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x19,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x22, 0xc7, 0x01,
	0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x74, 0x5f,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x70, 0x6f, 0x73, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x26, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x22, 0xba, 0x01, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x4e, 0x2e, 0x6e, 0x65, 0x77, 0x73,
	0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x31, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x01, 0x32, 0xfb, 0x01, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65,
	0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x62, 0x0a, 0x0b, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x6e, 0x65, 0x77,
	0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x80, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x31, 0x2e, 0x6e, 0x65, 0x77, 0x73,
	0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6e,
	0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69,
	0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x6c, 0x5a, 0x6a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x6f, 0x61, 0x6e, 0x67, 0x4e, 0x67, 0x75, 0x79, 0x65, 0x6e, 0x44, 0x65, 0x76, 0x33,
	0x2f, 0x57, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x70, 0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65,
	0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x3b, 0x6e, 0x65, 0x77,
	0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_types_proto_newsfeed_publishing_proto_rawDescOnce sync.Once
	file_pkg_types_proto_newsfeed_publishing_proto_rawDescData = file_pkg_types_proto_newsfeed_publishing_proto_rawDesc
)

func file_pkg_types_proto_newsfeed_publishing_proto_rawDescGZIP() []byte {
	file_pkg_types_proto_newsfeed_publishing_proto_rawDescOnce.Do(func() {
		file_pkg_types_proto_newsfeed_publishing_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_types_proto_newsfeed_publishing_proto_rawDescData)
	})
	return file_pkg_types_proto_newsfeed_publishing_proto_rawDescData
}

var file_pkg_types_proto_newsfeed_publishing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_types_proto_newsfeed_publishing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_types_proto_newsfeed_publishing_proto_goTypes = []interface{}{
	(PublishPostResponse_PublishPostResponseStatus)(0),             // 0: newsfeed_publishing.PublishPostResponse.PublishPostResponseStatus
	(UpdateEngagementScoreResponse_UpdateEngagementScoreStatus)(0), // 1: newsfeed_publishing.UpdateEngagementScoreResponse.UpdateEngagementScoreStatus
	(*PublishPostRequest)(nil),                                     // 2: newsfeed_publishing.PublishPostRequest
	(*PublishPostResponse)(nil),                                    // 3: newsfeed_publishing.PublishPostResponse
	(*UpdateEngagementScoreRequest)(nil),                           // 4: newsfeed_publishing.UpdateEngagementScoreRequest
	(*UpdateEngagementScoreResponse)(nil),                          // 5: newsfeed_publishing.UpdateEngagementScoreResponse
}
var file_pkg_types_proto_newsfeed_publishing_proto_depIdxs = []int32{
	0, // 0: newsfeed_publishing.PublishPostResponse.status:type_name -> newsfeed_publishing.PublishPostResponse.PublishPostResponseStatus
	1, // 1: newsfeed_publishing.UpdateEngagementScoreResponse.status:type_name -> newsfeed_publishing.UpdateEngagementScoreResponse.UpdateEngagementScoreStatus
	2, // 2: newsfeed_publishing.NewsfeedPublishing.PublishPost:input_type -> newsfeed_publishing.PublishPostRequest
	4, // 3: newsfeed_publishing.NewsfeedPublishing.UpdateEngagementScore:input_type -> newsfeed_publishing.UpdateEngagementScoreRequest
	3, // 4: newsfeed_publishing.NewsfeedPublishing.PublishPost:output_type -> newsfeed_publishing.PublishPostResponse
	5, // 5: newsfeed_publishing.NewsfeedPublishing.UpdateEngagementScore:output_type -> newsfeed_publishing.UpdateEngagementScoreResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_types_proto_newsfeed_publishing_proto_init() }
func file_pkg_types_proto_newsfeed_publishing_proto_init() {
	if File_pkg_types_proto_newsfeed_publishing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEngagementScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_types_proto_newsfeed_publishing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEngagementScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_types_proto_newsfeed_publishing_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_types_proto_newsfeed_publishing_proto_goTypes,
		DependencyIndexes: file_pkg_types_proto_newsfeed_publishing_proto_depIdxs,
		EnumInfos:         file_pkg_types_proto_newsfeed_publishing_proto_enumTypes,
		MessageInfos:      file_pkg_types_proto_newsfeed_publishing_proto_msgTypes,
	}.Build()
	File_pkg_types_proto_newsfeed_publishing_proto = out.File
	file_pkg_types_proto_newsfeed_publishing_proto_rawDesc = nil
	file_pkg_types_proto_newsfeed_publishing_proto_goTypes = nil
	file_pkg_types_proto_newsfeed_publishing_proto_depIdxs = nil
}
