// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: newsfeed_publishing.proto

package newsfeed_publishing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishPostResponse_PublishPostResponseStatus int32

const (
	PublishPostResponse_OK     PublishPostResponse_PublishPostResponseStatus = 0
	PublishPostResponse_FAILED PublishPostResponse_PublishPostResponseStatus = 1
)

// Enum value maps for PublishPostResponse_PublishPostResponseStatus.
var (
	PublishPostResponse_PublishPostResponseStatus_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	PublishPostResponse_PublishPostResponseStatus_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x PublishPostResponse_PublishPostResponseStatus) Enum() *PublishPostResponse_PublishPostResponseStatus {
	p := new(PublishPostResponse_PublishPostResponseStatus)
	*p = x
	return p
}

func (x PublishPostResponse_PublishPostResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishPostResponse_PublishPostResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_newsfeed_publishing_proto_enumTypes[0].Descriptor()
}

func (PublishPostResponse_PublishPostResponseStatus) Type() protoreflect.EnumType {
	return &file_newsfeed_publishing_proto_enumTypes[0]
}

func (x PublishPostResponse_PublishPostResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishPostResponse_PublishPostResponseStatus.Descriptor instead.
func (PublishPostResponse_PublishPostResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_newsfeed_publishing_proto_rawDescGZIP(), []int{1, 0}
}

type PublishPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishPostRequest) Reset() {
	*x = PublishPostRequest{}
	mi := &file_newsfeed_publishing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostRequest) ProtoMessage() {}

func (x *PublishPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newsfeed_publishing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostRequest.ProtoReflect.Descriptor instead.
func (*PublishPostRequest) Descriptor() ([]byte, []int) {
	return file_newsfeed_publishing_proto_rawDescGZIP(), []int{0}
}

func (x *PublishPostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PublishPostResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Status        PublishPostResponse_PublishPostResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=newsfeed_publishing.PublishPostResponse_PublishPostResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishPostResponse) Reset() {
	*x = PublishPostResponse{}
	mi := &file_newsfeed_publishing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostResponse) ProtoMessage() {}

func (x *PublishPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newsfeed_publishing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostResponse.ProtoReflect.Descriptor instead.
func (*PublishPostResponse) Descriptor() ([]byte, []int) {
	return file_newsfeed_publishing_proto_rawDescGZIP(), []int{1}
}

func (x *PublishPostResponse) GetStatus() PublishPostResponse_PublishPostResponseStatus {
	if x != nil {
		return x.Status
	}
	return PublishPostResponse_OK
}

var File_newsfeed_publishing_proto protoreflect.FileDescriptor

const file_newsfeed_publishing_proto_rawDesc = "" +
	"\n" +
	"\x19newsfeed_publishing.proto\x12\x13newsfeed_publishing\"F\n" +
	"\x12PublishPostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\"\xa2\x01\n" +
	"\x13PublishPostResponse\x12Z\n" +
	"\x06status\x18\x01 \x01(\x0e2B.newsfeed_publishing.PublishPostResponse.PublishPostResponseStatusR\x06status\"/\n" +
	"\x19PublishPostResponseStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012x\n" +
	"\x12NewsfeedPublishing\x12b\n" +
	"\vPublishPost\x12'.newsfeed_publishing.PublishPostRequest\x1a(.newsfeed_publishing.PublishPostResponse\"\x00BXZVgithub.com/hoangNguyenDev3/WanderSphere/backend/pkg/types/proto/pb/newsfeed_publishingb\x06proto3"

var (
	file_newsfeed_publishing_proto_rawDescOnce sync.Once
	file_newsfeed_publishing_proto_rawDescData []byte
)

func file_newsfeed_publishing_proto_rawDescGZIP() []byte {
	file_newsfeed_publishing_proto_rawDescOnce.Do(func() {
		file_newsfeed_publishing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_newsfeed_publishing_proto_rawDesc), len(file_newsfeed_publishing_proto_rawDesc)))
	})
	return file_newsfeed_publishing_proto_rawDescData
}

var file_newsfeed_publishing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_newsfeed_publishing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_newsfeed_publishing_proto_goTypes = []any{
	(PublishPostResponse_PublishPostResponseStatus)(0), // 0: newsfeed_publishing.PublishPostResponse.PublishPostResponseStatus
	(*PublishPostRequest)(nil),                         // 1: newsfeed_publishing.PublishPostRequest
	(*PublishPostResponse)(nil),                        // 2: newsfeed_publishing.PublishPostResponse
}
var file_newsfeed_publishing_proto_depIdxs = []int32{
	0, // 0: newsfeed_publishing.PublishPostResponse.status:type_name -> newsfeed_publishing.PublishPostResponse.PublishPostResponseStatus
	1, // 1: newsfeed_publishing.NewsfeedPublishing.PublishPost:input_type -> newsfeed_publishing.PublishPostRequest
	2, // 2: newsfeed_publishing.NewsfeedPublishing.PublishPost:output_type -> newsfeed_publishing.PublishPostResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_newsfeed_publishing_proto_init() }
func file_newsfeed_publishing_proto_init() {
	if File_newsfeed_publishing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_newsfeed_publishing_proto_rawDesc), len(file_newsfeed_publishing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newsfeed_publishing_proto_goTypes,
		DependencyIndexes: file_newsfeed_publishing_proto_depIdxs,
		EnumInfos:         file_newsfeed_publishing_proto_enumTypes,
		MessageInfos:      file_newsfeed_publishing_proto_msgTypes,
	}.Build()
	File_newsfeed_publishing_proto = out.File
	file_newsfeed_publishing_proto_goTypes = nil
	file_newsfeed_publishing_proto_depIdxs = nil
}
