# Common configurations for aap and nf
postgres: &POSTGRES
  dsn: "postgres:123456@tcp(postgres:5432)/wander_sphere?sslmode=disable"
  defaultStringSize: 256
  disableDatetimePrecision: true
  dontSupportRenameIndex: true
  skipInitializeWithVersion: false
redis: &REDIS
  addr: redis:6379

# Configuration for aap service connection
authenticate_and_post_config: &AAP
  port: 19001
  postgres: *POSTGRES
  redis: *REDIS

# Configuration for nf service connection
newsfeed_config: &NF
  port: 19002
  postgres: *POSTGRES
  redis: *REDIS

# Configurations for web app
web_config:
  # Connection configs
  port: 19003
  api_version: ["v1"]
  authenticate_and_post:
    hosts: ["aap:19001"]
  redis: *REDIS